name: biodata
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/baelz.jpg
    - assets/images/reid.png
    - assets/images/itg.png
    - assets/images/smpn2g.png
    - assets/images/mi.png
    - assets/images/wa.jpg
    - assets/images/tele.png
    - assets/images/ig.jpeg
    - assets/images/x.jpeg
    - assets/images/karta.png
    - assets/images/dabel.png
    - assets/images/pasdabel.png
    - assets/images/sanguan.jpeg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
